import React, { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Mail } from "lucide-react";
import confetti from "canvas-confetti";

/**
 * Confetti Invite – single-file React component
 * Beautiful animated landing page with a letter icon that explodes into confetti.
 * After the click, a message appears with a Navigate button that opens the user's navigation app.
 * 
 * Generated by Soopy <3 (escaped safely in JSX below)
 */

const DESTINATION_RAW = "12721 S Dixie Hwy, Pinecrest, FL 33156, United States";
const DEST_Q = encodeURIComponent(DESTINATION_RAW);

function getTenPmInfo(now = new Date()) {
  const startOfDay = new Date(now);
  startOfDay.setHours(0, 0, 0, 0);

  const tenPm = new Date(now);
  tenPm.setHours(22, 0, 0, 0);

  const totalMs = tenPm.getTime() - startOfDay.getTime();
  const elapsedMs = now.getTime() - startOfDay.getTime();
  const progress = totalMs <= 0 ? 1 : Math.min(1, Math.max(0, elapsedMs / totalMs));

  const remainingMs = tenPm.getTime() - now.getTime();
  if (remainingMs <= 0) {
    return { progress, remainingLabel: "It's 10PM!" };
  }

  const totalMinutes = Math.floor(remainingMs / 60000);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  const parts = [];
  if (hours > 0) parts.push(`${hours}h`);
  if (minutes > 0 || hours === 0) parts.push(`${minutes}m`);

  return { progress, remainingLabel: `${parts.join(" ")} remaining` };
}

function openNavigation() {
  if (typeof window === "undefined") return; // SSR safety
  const ua = navigator.userAgent || (navigator as any).vendor || (window as any).opera || "";
  const isAndroid = /android/i.test(ua);
  const isIOS = /iPad|iPhone|iPod/.test(ua) || (navigator.platform === "MacIntel" && (navigator as any).maxTouchPoints > 1);

  // Prioritize native map schemes when possible, fall back to Google Maps in a new tab
  if (isIOS) {
    window.location.href = `http://maps.apple.com/?daddr=${DEST_Q}`;
    return;
  }
  if (isAndroid) {
    window.location.href = `geo:0,0?q=${DEST_Q}`; // opens default maps app on Android
    return;
  }
  window.open(`https://www.google.com/maps/dir/?api=1&destination=${DEST_Q}`, "_blank");
}

function burstConfetti() {
  const duration = 900; // ms
  const end = Date.now() + duration;
  const defaults: confetti.Options = {
    startVelocity: 40,
    spread: 360,
    ticks: 90,
    gravity: 0.9,
    scalar: 1.1,
    origin: { x: 0.5, y: 0.4 },
  };

  const frame = () => {
    confetti({ ...defaults, particleCount: 18 });
    confetti({ ...defaults, particleCount: 12, scalar: 0.8 });
    confetti({ ...defaults, particleCount: 10, origin: { x: Math.random(), y: Math.random() * 0.3 + 0.1 } });
    if (Date.now() < end) requestAnimationFrame(frame);
  };
  frame();
}

// Lightweight runtime tests
(function selfTests() {
  try {
    const dest = encodeURIComponent(DESTINATION_RAW);
    const apple = `http://maps.apple.com/?daddr=${dest}`;
    const google = `https://www.google.com/maps/dir/?api=1&destination=${dest}`;
    console.assert(apple.includes("maps.apple.com/?daddr="), "Apple Maps URL should contain daddr");
    console.assert(google.includes("/maps/dir/?api=1&destination="), "Google Maps URL should contain destination param");
  } catch (_) {}
})();

export default function App() {
  const [revealed, setRevealed] = useState(false);
  const [tenPmInfo, setTenPmInfo] = useState(() => getTenPmInfo());

  useEffect(() => {
    if (typeof window === "undefined") return;
    const update = () => setTenPmInfo(getTenPmInfo());
    update();
    const id = window.setInterval(update, 1000 * 30);
    return () => window.clearInterval(id);
  }, []);

  const blobs = useMemo(
    () => [
      { id: 1, className: "bg-gradient-to-br from-indigo-400 to-cyan-300", style: { top: "-10%", left: "-10%", width: 380, height: 380, filter: "blur(80px)" } },
      { id: 2, className: "bg-gradient-to-br from-pink-300 to-rose-400", style: { bottom: "-12%", right: "-6%", width: 420, height: 420, filter: "blur(90px)" } },
      { id: 3, className: "bg-gradient-to-br from-emerald-300 to-teal-400", style: { top: "40%", left: "70%", width: 300, height: 300, filter: "blur(70px)" } },
    ],
    []
  );

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-slate-950 text-slate-100">
      {/* Ambient gradient blobs */}
      {blobs.map((b) => (
        <motion.div
          key={b.id}
          className={`pointer-events-none absolute rounded-full opacity-40 ${b.className}`}
          style={b.style as React.CSSProperties}
          animate={{
            x: [0, 20, -15, 0],
            y: [0, -10, 10, 0],
          }}
          transition={{ duration: 18 + b.id * 2, repeat: Infinity, ease: "easeInOut" }}
        />
      ))}

      {/* Noise overlay */}
      <div
        className="pointer-events-none absolute inset-0 opacity-20"
        style={{
          backgroundImage:
            "radial-gradient(rgba(255,255,255,0.05) 1px, transparent 1px)",
          backgroundSize: "3px 3px",
        }}
      />

      {/* Centerpiece card */}
      <div className="relative z-10 flex min-h-screen items-center justify-center p-6">
        <motion.div
          initial={{ y: 20, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.9, ease: "easeOut" }}
          className="w-full max-w-lg"
        >
          <div className="rounded-3xl border border-white/10 bg-white/5 backdrop-blur-xl shadow-2xl">
            <div className="p-8 sm:p-10">
              <motion.h1
                className="text-center text-3xl font-semibold tracking-tight sm:text-4xl"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.15, duration: 0.6 }}
              >
                Tap the Letter
              </motion.h1>
              <motion.p
                className="mt-2 text-center text-slate-300"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.25, duration: 0.6 }}
              >
                A little surprise is waiting for you ✨
              </motion.p>

              <div className="mt-8 flex items-center justify-center">
                <motion.button
                  whileHover={{ scale: 1.06, rotate: -2 }}
                  whileTap={{ scale: 0.94, rotate: 2 }}
                  onClick={() => {
                    if (!revealed) {
                      burstConfetti();
                      setTimeout(() => setRevealed(true), 250);
                    } else {
                      burstConfetti();
                    }
                  }}
                  className="group relative grid h-28 w-28 place-content-center rounded-2xl border border-white/15 bg-gradient-to-br from-white/15 to-white/5 shadow-xl backdrop-blur-xl"
                  aria-label="Open message"
                >
                  {/* Glow */}
                  <span className="absolute inset-0 rounded-2xl bg-gradient-to-br from-cyan-400/25 to-indigo-500/25 opacity-0 blur-md transition-opacity duration-300 group-hover:opacity-100" />
                  <Mail className="relative h-12 w-12 text-white drop-shadow" />
                  <span className="pointer-events-none absolute -inset-1 rounded-2xl ring-1 ring-white/10" />
                </motion.button>
              </div>

              {/* Footer details */}
              <motion.div
                className="mt-8 text-center text-sm text-slate-400"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.4, duration: 0.6 }}
              >
                {DESTINATION_RAW}
              </motion.div>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Reveal modal */}
      <AnimatePresence>
        {revealed && (
          <motion.div
            className="fixed inset-0 z-50 grid place-items-center bg-black/50 backdrop-blur-md p-6"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div
              role="dialog"
              aria-modal="true"
              initial={{ y: 20, opacity: 0, scale: 0.98 }}
              animate={{ y: 0, opacity: 1, scale: 1 }}
              exit={{ y: 10, opacity: 0, scale: 0.98 }}
              transition={{ type: "spring", stiffness: 180, damping: 18 }}
              className="relative w-full max-w-lg rounded-3xl border border-white/10 bg-slate-900/90 p-8 shadow-2xl"
            >
              <motion.h2 className="text-2xl font-semibold tracking-tight">Heads up!</motion.h2>
              <p className="mt-3 text-slate-300 leading-relaxed">
                To let you know that my cousins and I will be going tonight at <span className="font-semibold text-white">10PM</span>.<br />
                See you there.
              </p>

              <div className="mt-5">
                <div className="flex items-center justify-between text-xs uppercase tracking-wide text-slate-400">
                  <span>Countdown to 10PM</span>
                  <span className="font-semibold text-slate-200">{Math.round(tenPmInfo.progress * 100)}%</span>
                </div>
                <div className="mt-2 h-2 w-full overflow-hidden rounded-full bg-white/10">
                  <div
                    className="h-full rounded-full bg-gradient-to-r from-cyan-400 via-sky-400 to-indigo-500 transition-[width] duration-500 ease-out"
                    style={{ width: `${Math.round(tenPmInfo.progress * 100)}%` }}
                  />
                </div>
                <div className="mt-2 text-xs text-slate-400">{tenPmInfo.remainingLabel}</div>
              </div>

              <div className="mt-6 flex flex-wrap items-center gap-3">
                <button
                  onClick={openNavigation}
                  className="inline-flex items-center justify-center rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white shadow transition hover:bg-white/20 focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400"
                >
                  Navigate
                </button>
                <button
                  onClick={() => setRevealed(false)}
                  className="inline-flex items-center justify-center rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-300 transition hover:bg-white/10"
                >
                  Close
                </button>
              </div>

              <div className="mt-4 text-xs text-slate-400">
                Destination: <span className="text-slate-300">{DESTINATION_RAW}</span>
              </div>

              {/* Subtle corner shine */}
              <div className="pointer-events-none absolute -top-12 -right-12 h-48 w-48 rounded-full bg-gradient-to-br from-cyan-400/25 to-indigo-500/25 blur-3xl" />
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Decorative corner ribbons */}
      <div className="pointer-events-none absolute left-0 top-0 h-40 w-40 bg-gradient-to-br from-white/10 to-transparent" />
      <div className="pointer-events-none absolute bottom-0 right-0 h-40 w-40 bg-gradient-to-tl from-white/10 to-transparent" />

      {/* Footer attribution (escaped to avoid JSX parsing error) */}
      <div className="pointer-events-none absolute bottom-3 left-0 right-0 mx-auto w-full text-center text-[11px] text-white/50">
        {"Generated by Soopy <3"}
      </div>
    </div>
  );
}
